all:
	latex apertium-sh-mk
	bibtex apertium-sh-mk
	latex apertium-sh-mk
	latex apertium-sh-mk
	pdflatex apertium-sh-mk
clean:
	rm apertium-sh-mk.aux apertium-sh-mk.log apertium-sh-mk.toc apertium-sh-mk.bbl apertium-sh-mk.blg apertium-sh-mk.pdf apertium-sh-mk.dvi apertium-sh-mk.idx
